#!/usr/bin/env python3
"""
GitHub Integration Example

This example shows how the GitHub repository creation functionality
can be integrated with the existing WhatsApp agent workflow.
"""

from datetime import datetime
from src.logger import logger
from src.github_api import GitHubAPI
from src.content_scraper import scrape_all_sources
import json
import os


def create_news_repository():
    """
    Create a GitHub repository to store daily tech news summaries.
    This demonstrates practical use of the GitHub API functionality.
    """
    try:
        github_api = GitHubAPI()
        
        # Create a repository for storing tech news
        timestamp = datetime.now().strftime("%Y-%m")
        repo_name = f"tech-news-{timestamp}"
        description = f"Daily tech news summaries for {datetime.now().strftime('%B %Y')} - Generated by myWAgent"
        
        logger.info(f"🆕 Creating repository: {repo_name}")
        repo_data = github_api.create_repository(
            name=repo_name,
            description=description,
            private=False,
            auto_init=True
        )
        
        if repo_data:
            logger.info(f"✅ Repository created: {repo_data['html_url']}")
            return repo_data
        else:
            logger.error("❌ Failed to create repository")
            return None
            
    except ValueError as e:
        logger.error(f"Configuration error: {e}")
        return None
    except Exception as e:
        logger.error(f"Unexpected error: {e}")
        return None


def create_project_repository(project_name, description="", private=False):
    """
    Create a general-purpose project repository.
    
    Args:
        project_name (str): Name of the project
        description (str): Project description
        private (bool): Whether to make the repository private
    
    Returns:
        dict: Repository data if successful, None otherwise
    """
    try:
        github_api = GitHubAPI()
        
        logger.info(f"🆕 Creating project repository: {project_name}")
        repo_data = github_api.create_repository(
            name=project_name,
            description=description,
            private=private,
            auto_init=True
        )
        
        if repo_data:
            logger.info(f"✅ Project repository created: {repo_data['html_url']}")
            logger.info(f"📁 Repository name: {repo_data['name']}")
            logger.info(f"🔒 Private: {repo_data['private']}")
            return repo_data
        else:
            logger.error("❌ Failed to create project repository")
            return None
            
    except ValueError as e:
        logger.error(f"Configuration error: {e}")
        logger.error("Please set GITHUB_API_TOKEN in your .env file")
        return None
    except Exception as e:
        logger.error(f"Unexpected error: {e}")
        return None


def list_user_repositories_summary():
    """Get a summary of user's repositories."""
    try:
        github_api = GitHubAPI()
        
        # Get user info
        user_info = github_api.get_user_info()
        if user_info:
            logger.info(f"👤 GitHub User: {user_info.get('login', 'Unknown')}")
            logger.info(f"📊 Total public repositories: {user_info.get('public_repos', 0)}")
            logger.info(f"👥 Followers: {user_info.get('followers', 0)}")
            logger.info(f"👤 Following: {user_info.get('following', 0)}")
        
        # List recent repositories
        repos = github_api.list_repositories(per_page=5)
        if repos:
            logger.info(f"\n📚 Recent repositories ({len(repos)} shown):")
            for i, repo in enumerate(repos, 1):
                logger.info(f"  {i}. {repo['name']}")
                logger.info(f"     🔗 {repo['html_url']}")
                if repo['description']:
                    logger.info(f"     📝 {repo['description'][:100]}...")
                logger.info(f"     🔒 Private: {repo['private']}")
                logger.info(f"     📅 Updated: {repo['updated_at']}")
                logger.info("")
        
        return user_info, repos
        
    except ValueError as e:
        logger.error(f"Configuration error: {e}")
        return None, None
    except Exception as e:
        logger.error(f"Unexpected error: {e}")
        return None, None


def demo_integration_workflow():
    """
    Demonstrate integration between news scraping and GitHub repository creation.
    This shows how the GitHub functionality can enhance the existing workflow.
    """
    logger.info("🚀 Starting GitHub Integration Demo")
    logger.info("=" * 60)
    
    # Step 1: Check GitHub connectivity
    logger.info("📋 Step 1: Checking GitHub connectivity...")
    user_info, repos = list_user_repositories_summary()
    
    if not user_info:
        logger.error("❌ Cannot connect to GitHub. Please check your GITHUB_API_TOKEN.")
        return False
    
    # Step 2: Scrape some news (without external requests for demo)
    logger.info("\n📰 Step 2: Simulating news scraping...")
    # We'll simulate this to avoid making external requests in the demo
    sample_news = {
        "TechCrunch": [
            {"headline": "AI Breakthrough in Repository Management", "url": "https://example.com/1"},
            {"headline": "New GitHub Features for Developers", "url": "https://example.com/2"}
        ]
    }
    logger.info(f"Found {len(sample_news['TechCrunch'])} sample articles")
    
    # Step 3: Create a repository for storing news data
    logger.info("\n📁 Step 3: Creating repository for news storage...")
    # Uncomment the next line to actually create a repository
    # news_repo = create_news_repository()
    logger.info("🎭 Repository creation simulated (uncomment to create real repo)")
    
    # Step 4: Show how to create project repositories
    logger.info("\n🛠️  Step 4: Demonstrating project repository creation...")
    project_examples = [
        {
            "name": "ai-news-classifier",
            "description": "AI model for classifying tech news articles",
            "private": False
        },
        {
            "name": "whatsapp-automation-tools", 
            "description": "Tools for WhatsApp business automation",
            "private": True
        }
    ]
    
    for project in project_examples:
        logger.info(f"📝 Example: {project['name']}")
        logger.info(f"    Description: {project['description']}")
        logger.info(f"    Private: {project['private']}")
        # Uncomment to create actual repositories:
        # create_project_repository(**project)
    
    logger.info("\n" + "=" * 60)
    logger.info("✅ Integration demo completed!")
    logger.info("💡 This shows how GitHub repository creation can enhance your workflow")
    return True


if __name__ == "__main__":
    demo_integration_workflow()